export default [
    {
        "slug": "department-of-philosophy",
        "name": "Department of Philosophy",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://philosophy.du.ac.in",
        "email": "head@philosophy.du.ac.in",
        "phone": "+91-11-27666792",
        "address": "Faculty of Arts, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Arts",
        "shortHistory": "The Department of Philosophy is known for excellence in Indian philosophy, Western philosophy, ethics, logic, political philosophy, and applied philosophy. It encourages critical thinking, analytical reasoning, and interdisciplinary research."
    },
    {
        "slug": "department-of-psychology",
        "name": "Department of Psychology",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://psychology.du.ac.in",
        "email": "head@psychology.du.ac.in",
        "phone": "+91-11-27666613",
        "address": "Faculty of Arts, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Arts",
        "shortHistory": "The Department of Psychology offers programmes in clinical, counselling, organizational, educational, and experimental psychology. It promotes research and practical training through laboratories, fieldwork, and psychological assessment."
    },
    {
        "slug": "department-of-arabic",
        "name": "Department of Arabic",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://arabic.du.ac.in",
        "email": "head@arabic.du.ac.in",
        "phone": "+91-11-27666640",
        "address": "Faculty of Arts, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Arts",
        "shortHistory": "The Department of Arabic promotes the study of Arabic language, literature, translation, and Middle Eastern culture. It offers undergraduate, postgraduate, and doctoral programmes while encouraging research in classical and modern Arabic studies."
    },
    {
        "slug": "department-of-buddhist-studies",
        "name": "Department of Buddhist Studies",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://buddhist.du.ac.in",
        "email": "head@buddhist.du.ac.in",
        "phone": "+91-11-27666628",
        "address": "Faculty of Arts, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Arts",
        "shortHistory": "The Department of Buddhist Studies is one of India's leading centres for the study of Buddhism, Buddhist philosophy, history, culture, and Pali literature. The department offers postgraduate and doctoral programmes and promotes interdisciplinary research."
    },
    {
        "slug": "department-of-english",
        "name": "Department of English",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://english.du.ac.in",
        "email": "head@english.du.ac.in",
        "phone": "+91-11-27666757",
        "address": "Faculty of Arts, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Arts",
        "shortHistory": "The Department of English is among the most prestigious departments at the University of Delhi. It offers programmes in English literature, literary theory, linguistics, and cultural studies while actively promoting research, seminars, and international academic collaborations."
    },
    {
        "slug": "department-of-germanic-romance-studies",
        "name": "Department of Germanic & Romance Studies",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://grs.du.ac.in",
        "email": "head@grs.du.ac.in",
        "phone": "+91-11-27666795",
        "address": "Faculty of Arts, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Arts",
        "shortHistory": "The Department of Germanic and Romance Studies provides education in German, French, Spanish, Italian, and other European languages. It emphasizes language proficiency, literature, translation, and intercultural studies."
    },
    {
        "slug": "department-of-hindi",
        "name": "Department of Hindi",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://hindi.du.ac.in",
        "email": "head@hindi.du.ac.in",
        "phone": "+91-11-27666675",
        "address": "Faculty of Arts, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Arts",
        "shortHistory": "The Department of Hindi is a nationally renowned centre for the study of Hindi language, literature, criticism, journalism, and translation. It contributes significantly to research and the promotion of Indian literary traditions."
    },
    {
        "slug": "department-of-library-information-science",
        "name": "Department of Library & Information Science",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://lis.du.ac.in",
        "email": "head@lis.du.ac.in",
        "phone": "+91-11-27666744",
        "address": "Faculty of Arts, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Arts",
        "shortHistory": "The Department of Library and Information Science prepares students for careers in library management, digital information systems, archives, and knowledge management. It combines traditional library science with modern information technology."
    },
    {
        "slug": "department-of-linguistics",
        "name": "Department of Linguistics",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://linguistics.du.ac.in",
        "email": "head@linguistics.du.ac.in",
        "phone": "+91-11-27666796",
        "address": "Faculty of Arts, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Arts",
        "shortHistory": "The Department of Linguistics focuses on language structure, phonetics, syntax, semantics, sociolinguistics, and computational linguistics. It promotes research on Indian and global languages through interdisciplinary approaches."
    },
    {
        "slug": "department-of-persian",
        "name": "Department of Persian",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://persian.du.ac.in",
        "email": "head@persian.du.ac.in",
        "phone": "+91-11-27666645",
        "address": "Faculty of Arts, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Arts",
        "shortHistory": "The Department of Persian offers education in Persian language, literature, history, and Indo-Persian cultural heritage. It plays an important role in preserving and promoting classical Persian studies in India."
    },
    {
        "slug": "department-of-punjabi",
        "name": "Department of Punjabi",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://punjabi.du.ac.in",
        "email": "head@punjabi.du.ac.in",
        "phone": "+91-11-27666734",
        "address": "Faculty of Arts, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Arts",
        "shortHistory": "The Department of Punjabi is dedicated to the study of Punjabi language, literature, culture, and history. It offers postgraduate and doctoral programmes while promoting research in Punjabi literary traditions, folklore, linguistics, and cultural studies. The department also organizes seminars, literary festivals, and academic discussions to preserve and promote Punjabi heritage."
    },
    {
        "slug": "department-of-sanskrit",
        "name": "Department of Sanskrit",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://sanskrit.du.ac.in",
        "email": "head@sanskrit.du.ac.in",
        "phone": "+91-11-27666636",
        "address": "Faculty of Arts, University of Delhi, North Campus, Delhi - 110007",
        "faculty": "Faculty of Arts",
        "shortHistory": "The Department of Sanskrit is one of India's premier centres for the study of classical Sanskrit language, literature, philosophy, grammar, and ancient Indian knowledge systems. It offers undergraduate, postgraduate, and doctoral programmes while encouraging research on India's rich intellectual and cultural traditions."
    },
    {
        "slug": "department-of-slavonic-finno-ugrian-studies",
        "name": "Department of Slavonic & Finno-Ugrian Studies",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://slavic.du.ac.in",
        "email": "head@slavic.du.ac.in",
        "phone": "+91-11-27666798",
        "address": "Faculty of Arts, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Arts",
        "shortHistory": "The Department of Slavonic & Finno-Ugrian Studies specializes in the teaching of Russian and other Central and Eastern European languages and cultures. It promotes linguistic proficiency, literary studies, translation, and international academic exchange, helping students build careers in diplomacy, education, and international relations."
    },
    {
        "slug": "department-of-urdu",
        "name": "Department of Urdu",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://urdu.du.ac.in",
        "email": "head@urdu.du.ac.in",
        "phone": "+91-11-27666646",
        "address": "Faculty of Arts, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Arts",
        "shortHistory": "The Department of Urdu is recognized for its excellence in teaching Urdu language, literature, linguistics, poetry, and literary criticism. It offers undergraduate, postgraduate, and doctoral programmes while contributing significantly to research and the preservation of India's Urdu literary heritage."
    },
    {
        "slug": "department-of-indian-languages-literary-studies",
        "name": "Department of Indian Languages & Literary Studies",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://ils.du.ac.in",
        "email": "head@ils.du.ac.in",
        "phone": "+91-11-27666762",
        "address": "Faculty of Arts, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Arts",
        "shortHistory": "The Department of Indian Languages & Literary Studies promotes the comparative study of Indian languages, literature, translation, and cultural traditions. It encourages interdisciplinary research, linguistic diversity, and literary scholarship, fostering a deeper understanding of India's multilingual and multicultural heritage."
    },
    {
        "slug": "department-of-adult-continuing-education-extension",
        "name": "Department of Adult, Continuing Education & Extension",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://dacee.du.ac.in",
        "email": "head@ace.du.ac.in",
        "phone": "+91-11-27667280",
        "address": "Faculty of Social Sciences, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Social Sciences",
        "shortHistory": "The Department of Adult, Continuing Education & Extension promotes lifelong learning, community development, and social outreach. It offers postgraduate and doctoral programmes while conducting extension activities, skill development initiatives, and research focused on inclusive education and social empowerment."
    },
    {
        "slug": "department-of-economics",
        "name": "Department of Economics",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://econdse.org",
        "email": "head@economics.du.ac.in",
        "phone": "+91-11-27667725",
        "address": "Delhi School of Economics, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Social Sciences",
        "shortHistory": "The Department of Economics, popularly known as the Delhi School of Economics (DSE), is among India's most prestigious centres for economic education and research. It offers postgraduate and doctoral programmes while contributing significantly to research in development economics, public policy, econometrics, finance, and international trade."
    },
    {
        "slug": "department-of-geography",
        "name": "Department of Geography",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://geography.du.ac.in",
        "email": "head@geography.du.ac.in",
        "phone": "+91-11-27666491",
        "address": "Faculty of Social Sciences, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Social Sciences",
        "shortHistory": "The Department of Geography offers advanced education in physical geography, human geography, environmental studies, remote sensing, GIS, and urban planning. It combines classroom learning with fieldwork and research to address geographical and environmental challenges."
    },
    {
        "slug": "department-of-history",
        "name": "Department of History",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://history.du.ac.in",
        "email": "head@history.du.ac.in",
        "phone": "+91-11-27666659",
        "address": "Faculty of Social Sciences, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Social Sciences",
        "shortHistory": "The Department of History is internationally recognized for its contributions to historical research and teaching. It offers postgraduate and doctoral programmes covering ancient, medieval, modern, and contemporary history while encouraging critical inquiry through archives, field studies, and academic seminars."
    },
    {
        "slug": "department-of-political-science",
        "name": "Department of Political Science",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://www.polscience.du.ac.in",
        "email": "polscience.du@gmail.com",
        "phone": "+91-11-27666670",
        "address": "2nd Floor, Faculty of Social Sciences, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Social Sciences",
        "shortHistory": "The Department of Political Science is one of India's leading centres for the study of political theory, comparative politics, public administration, international relations, and public policy. The department is known for its distinguished faculty, impactful research, and active engagement with contemporary political issues."
    },
    {
        "slug": "department-of-social-work",
        "name": "Department of Social Work",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://socialwork.du.ac.in",
        "email": "head@socialwork.du.ac.in",
        "phone": "+91-11-27667881",
        "address": "Faculty of Social Sciences, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Social Sciences",
        "shortHistory": "The Department of Social Work prepares students to become professional social workers through rigorous academic training and fieldwork. It focuses on community development, social justice, public health, child welfare, gender studies, and policy interventions aimed at improving the lives of marginalized communities."
    },
    {
        "slug": "department-of-sociology",
        "name": "Department of Sociology",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://sociology.du.ac.in",
        "email": "head@sociology.du.ac.in",
        "phone": "+91-11-27667858",
        "address": "Faculty of Social Sciences, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Social Sciences",
        "shortHistory": "The Department of Sociology is one of India's foremost centres for sociological teaching and research. It offers postgraduate and doctoral programmes with specialization in social theory, gender studies, urbanization, rural society, caste, family, culture, and development. The department has made significant contributions to the understanding of Indian society through pioneering research and academic excellence."
    },
    {
        "slug": "department-of-african-studies",
        "name": "Department of African Studies",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://as.du.ac.in",
        "email": "head@as.du.ac.in",
        "phone": "+91-11-27666673",
        "address": "Faculty of Social Sciences, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Social Sciences",
        "shortHistory": "The Department of African Studies is a leading centre for the study of Africa's history, politics, economy, culture, and international relations. It promotes interdisciplinary research and strengthens India's academic and diplomatic engagement with African nations through teaching, seminars, and collaborative projects."
    },
    {
        "slug": "delhi-school-of-journalism",
        "name": "Delhi School of Journalism",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://dsj.du.ac.in",
        "email": "head@dsj.du.ac.in",
        "phone": "+91-9811098070",
        "address": "Faculty of Social Sciences, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Social Sciences",
        "shortHistory": "The Delhi School of Journalism is a premier institution offering professional education in journalism and mass communication. It equips students with practical and theoretical knowledge in print, broadcast, and digital media through industry-oriented training, internships, and media research."
    },
    {
        "slug": "department-of-east-asian-studies",
        "name": "Department of East Asian Studies",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://fss.du.ac.in/east.html",
        "email": "head@eas.du.ac.in",
        "phone": "+91-11-27666675",
        "address": "Faculty of Social Sciences, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Social Sciences",
        "shortHistory": "The Department of East Asian Studies specializes in the languages, politics, economics, history, and cultures of East Asian countries, particularly China, Japan, and Korea. It promotes international collaboration and prepares students for careers in academia, diplomacy, international business, and policy research."
    },
    {
        "slug": "department-of-anthropology",
        "name": "Department of Anthropology",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://anthro.du.ac.in",
        "email": "head@anthro.du.ac.in",
        "phone": "+91-11-27667329",
        "address": "Faculty of Science, University of Delhi, North Campus, Delhi - 110007",
        "faculty": "Faculty of Science",
        "shortHistory": "The Department of Anthropology is one of India's leading centres for the study of human evolution, biological anthropology, archaeology, forensic anthropology, and socio-cultural anthropology. The department integrates scientific research with fieldwork to understand human diversity and development."
    },
    {
        "slug": "department-of-botany",
        "name": "Department of Botany",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://botany.du.ac.in",
        "email": "head@botany.du.ac.in",
        "phone": "+91-11-27667573",
        "address": "Faculty of Science, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Science",
        "shortHistory": "The Department of Botany is a renowned centre for teaching and research in plant sciences. It offers programmes in plant physiology, ecology, genetics, biotechnology, taxonomy, and molecular biology while encouraging research in biodiversity conservation and sustainable development."
    },
    {
        "slug": "department-of-chemistry",
        "name": "Department of Chemistry",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://chemistry.du.ac.in",
        "email": "head@chemistry.du.ac.in",
        "phone": "+91-11-27667794",
        "address": "Faculty of Science, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Science",
        "shortHistory": "The Department of Chemistry is internationally recognized for excellence in chemical sciences. It offers specialized education in organic, inorganic, physical, analytical, and medicinal chemistry while promoting advanced research in materials science, nanotechnology, catalysis, and environmental chemistry."
    },
    {
        "slug": "department-of-environmental-studies",
        "name": "Department of Environmental Studies",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://es.du.ac.in",
        "email": "head@es.du.ac.in",
        "phone": "+91-11-27667125",
        "address": "Faculty of Science, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Science",
        "shortHistory": "The Department of Environmental Studies focuses on environmental conservation, climate change, biodiversity, sustainability, and environmental policy. Through research, fieldwork, and community engagement, the department prepares students to address global environmental challenges and promote sustainable development."
    },
    {
        "slug": "department-of-geology",
        "name": "Department of Geology",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://geology.du.ac.in",
        "email": "head@geology.du.ac.in",
        "phone": "+91-11-27667073",
        "address": "Faculty of Science, University of Delhi, North Campus, Delhi - 110007",
        "faculty": "Faculty of Science",
        "shortHistory": "The Department of Geology provides comprehensive education in earth sciences, mineralogy, petrology, structural geology, palaeontology, and geophysics. The department emphasizes field investigations, laboratory training, and research to understand Earth's processes and natural resources."
    },
    {
        "slug": "department-of-home-science",
        "name": "Department of Home Science",
        "campus": "NA",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://www.ladyirwin.edu.in",
        "email": "director@lic.du.ac.in",
        "phone": "+91-11-23711222",
        "address": "Lady Irwin College, Sikandra Road, New Delhi - 110001.",
        "faculty": "Faculty of Science",
        "shortHistory": "The Department of Home Science, based at Lady Irwin College, is a leading centre for education in nutrition, human development, resource management, textiles, food technology, and community health. It combines scientific knowledge with practical application to improve individual and community well-being."
    },
    {
        "slug": "department-of-nursing",
        "name": "Department of Nursing",
        "campus": "NA",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://www.du.ac.in/index.php?page=faculty-of-science",
        "email": "NA",
        "phone": "+91-11-26435397, +91-11-26436788",
        "address": "Faculty of Science, University of Delhi, Delhi.",
        "faculty": "Faculty of Science",
        "shortHistory": "The Department of Nursing provides professional education and training in nursing sciences, healthcare management, patient care, and community health. The department aims to develop competent healthcare professionals through academic excellence, clinical practice, and research."
    },
    {
        "slug": "department-of-pharmacy",
        "name": "Department of Pharmacy",
        "campus": "NA",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://www.du.ac.in/index.php?page=faculty-of-science",
        "email": "NA",
        "phone": "+91-11-26563342, +91-11-26563771, +91-11-24364213",
        "address": "Faculty of Science, University of Delhi, Delhi.",
        "faculty": "Faculty of Science",
        "shortHistory": "The Department of Pharmacy is dedicated to pharmaceutical education and research in pharmacology, pharmaceutics, medicinal chemistry, pharmacognosy, and pharmaceutical analysis. It promotes innovation in drug discovery, healthcare, and pharmaceutical sciences."
    },
    {
        "slug": "department-of-physics-astrophysics",
        "name": "Department of Physics & Astrophysics",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://physics.du.ac.in",
        "email": "head@physics.du.ac.in",
        "phone": "+91-11-27666796",
        "address": "Faculty of Science, University of Delhi, North Campus, Delhi - 110007",
        "faculty": "Faculty of Science",
        "shortHistory": "The Department of Physics & Astrophysics is one of India's premier centres for education and research in theoretical and experimental physics. It offers advanced studies in quantum mechanics, condensed matter physics, electronics, astrophysics, nuclear physics, and photonics while supporting cutting-edge scientific research."
    },
    {
        "slug": "department-of-zoology",
        "name": "Department of Zoology",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://zoology.du.ac.in",
        "email": "head@zoology.du.ac.in",
        "phone": "+91-11-27667985",
        "address": "Faculty of Science, University of Delhi, North Campus, Delhi - 110007.",
        "faculty": "Faculty of Science",
        "shortHistory": "The Department of Zoology is recognized for excellence in animal sciences, genetics, ecology, wildlife biology, physiology, and biotechnology. It combines laboratory research and field studies to advance knowledge in biodiversity conservation, biomedical sciences, and environmental sustainability."
    },
    {
        "slug": "department-of-computer-science",
        "name": "Department of Computer Science",
        "campus": "NA",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://cs.du.ac.in",
        "email": "office@cs.du.ac.in",
        "phone": "+91-11-27667591, +91-11-27667059, +91-11-27667725",
        "address": "Department of Computer Science, Faculty of Mathematical Sciences, New Academic Block, University of Delhi, Delhi - 110007.",
        "faculty": "Faculty of Mathematical Sciences",
        "shortHistory": "The Department of Computer Science is a premier centre for teaching and research in computer science and information technology. It offers undergraduate, postgraduate, and doctoral programmes covering artificial intelligence, machine learning, cybersecurity, software engineering, data science, cloud computing, and computer networks. The department promotes innovation through research projects, industry collaborations, and technical workshops."
    },
    {
        "slug": "department-of-mathematics",
        "name": "Department of Mathematics",
        "campus": "NA",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://maths.du.ac.in",
        "email": "head@maths.du.ac.in",
        "phone": "+91-11-27666658",
        "address": "Department of Mathematics, Faculty of Mathematical Sciences, Guru Tegh Bahadur Road, University of Delhi, Delhi - 110007.",
        "faculty": "Faculty of Mathematical Sciences",
        "shortHistory": "The Department of Mathematics is one of India's most distinguished mathematics departments, offering undergraduate, postgraduate, and doctoral programmes. It specializes in algebra, analysis, geometry, topology, differential equations, mathematical modelling, cryptography, optimization, and computational mathematics. The department actively promotes high-quality research through national and international collaborations."
    },
    {
        "slug": "department-of-operational-research",
        "name": "Department of Operational Research",
        "campus": "NA",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://or.du.ac.in",
        "email": "head@or.du.ac.in",
        "phone": "+91-11-27666672",
        "address": "Department of Operational Research, Faculty of Mathematical Sciences, University of Delhi, Delhi - 110007.",
        "faculty": "Faculty of Mathematical Sciences",
        "shortHistory": "The Department of Operational Research is a pioneer in the application of mathematical and analytical techniques for solving complex real-world problems. It offers programmes in optimization, data analytics, supply chain management, decision sciences, financial modelling, and business analytics. The department prepares students for careers in consulting, logistics, finance, analytics, and research."
    },
    {
        "slug": "department-of-statistics",
        "name": "Department of Statistics",
        "campus": "NA",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://statistics.du.ac.in",
        "email": "head@statistics.du.ac.in",
        "phone": "+91-11-27666634",
        "address": "Department of Statistics, Faculty of Mathematical Sciences, University of Delhi, Delhi - 110007.",
        "faculty": "Faculty of Mathematical Sciences",
        "shortHistory": "The Department of Statistics is one of the foremost centres for statistical education and research in India. It offers undergraduate, postgraduate, and doctoral programmes focusing on probability theory, biostatistics, econometrics, actuarial science, data analytics, machine learning, and statistical computing. The department equips students with analytical skills applicable across research, government, healthcare, banking, and technology sectors."
    },
    {
        "slug": "department-of-commerce",
        "name": "Department of Commerce",
        "campus": "NA",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://www.commerce.du.ac.in",
        "email": "office@commerce.du.ac.in",
        "phone": "+91-11-27667891 / +91-11-27667725 (Ext. 1630)",
        "address": "Department of Commerce Faculty of Commerce & Business Studies Delhi School of Economics Campus University of Delhi Delhi - 110007",
        "faculty": "Faculty of Commerce & Business Studies",
        "shortHistory": "The Department of Commerce is the only academic department under the Faculty of Commerce & Business Studies and is among India's leading institutions for commerce and management education. It offers M.Com., Ph.D., MBA (International Business), MBA (Human Resource Development), and MBA (Business Analytics) programmes. The department is known for its strong industry connections, research culture, experienced faculty, and excellent placement opportunities. Through seminars, workshops, internships, corporate interactions, and research initiatives, it equips students with the knowledge and professional skills required to excel in today's dynamic business environment."
    },
    {
        "slug": "department-of-finance-and-business-economics-fbe",
        "name": "Department of Finance and Business Economics (FBE)",
        "campus": "South",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://www.dbe-du.org",
        "email": "mbeadmindu@gmail.com",
        "phone": "+91-11-24111141",
        "address": "Department of Finance and Business Economics Faculty of Applied Social Sciences & Humanities University of Delhi, South Campus Benito Juarez Road, New Delhi - 110021.",
        "faculty": "Faculty of Applied Social Sciences & Humanities",
        "shortHistory": "The Department of Finance and Business Economics (FBE) is one of the University's premier departments specializing in finance, economics, business analytics, and management studies. Established in 1987, the department has earned a strong reputation for academic excellence and industry-oriented education. It offers undergraduate, postgraduate, and doctoral programmes, including B.A. (Hons.) Business Economics, MBA (Business Economics), and Ph.D. programmes. The curriculum combines theoretical knowledge with practical exposure through case studies, research projects, internships, seminars, and industry interactions, preparing students for careers in banking, consulting, financial services, corporate management, public policy, and entrepreneurship. The department is also actively involved in research and collaborates with industry and government organizations on projects related to finance, economics, and business strategy."
    },
    {
        "slug": "department-of-education-central-institute-of-education",
        "name": "Department of Education (Central Institute of Education)",
        "campus": "NA",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://cie.du.ac.in",
        "email": "head.dean@cie.du.ac.in",
        "phone": "+91-11-27667509, +91-11-27667030",
        "address": "Department of Education (Central Institute of Education) 33, Chhatra Marg University of Delhi Delhi - 110007",
        "faculty": "Faculty of Education",
        "shortHistory": "The Department of Education, popularly known as the Central Institute of Education (CIE), is among the oldest and most prestigious teacher education institutions in India. It offers programmes such as B.Ed., M.Ed., M.Phil. (where applicable), and Ph.D., focusing on teacher preparation, educational psychology, curriculum studies, guidance and counselling, educational administration, assessment, and educational research. The department is renowned for its innovative teaching methods, extensive field engagement, and contributions to educational reforms at both national and international levels. Through seminars, workshops, research projects, and collaborations with schools and educational organizations, CIE continues to advance excellence in teaching and learning while preparing future educators and academic leaders."
    },
    {
        "slug": "department-of-biochemistry",
        "name": "Department of Biochemistry",
        "campus": "South",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://biochemistry.du.ac.in",
        "email": "head@biochemistry.du.ac.in",
        "phone": "+91-11-27662446",
        "address": "Department of Biochemistry Faculty of Interdisciplinary & Applied Sciences University of Delhi, South Campus New Delhi - 110021",
        "faculty": "Faculty of Interdisciplinary & Applied Sciences",
        "shortHistory": "The Department of Biochemistry is a leading centre for teaching and research in molecular biology, enzymology, genetics, immunology, biotechnology, and biomedical sciences. It offers undergraduate, postgraduate, and doctoral programmes while promoting cutting-edge research in health sciences, disease mechanisms, and biotechnology. The department actively collaborates with research institutes and industries to encourage scientific innovation."
    },
    {
        "slug": "department-of-biophysics",
        "name": "Department of Biophysics",
        "campus": "South",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://biophysics.du.ac.in",
        "email": "head@biophysics.du.ac.in",
        "phone": "+91-11-24117517",
        "address": "Department of Biophysics Faculty of Interdisciplinary & Applied Sciences University of Delhi, South Campus New Delhi - 110021",
        "faculty": "Faculty of Interdisciplinary & Applied Sciences",
        "shortHistory": "The Department of Biophysics focuses on the application of physics to biological systems. It offers postgraduate and doctoral programmes covering structural biology, molecular biophysics, bioinformatics, medical physics, and computational biology. The department is recognized for its advanced research facilities and interdisciplinary collaborations in life sciences and healthcare."
    },
    {
        "slug": "department-of-electronic-science",
        "name": "Department of Electronic Science",
        "campus": "South",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://electronics.du.ac.in",
        "email": "head@electronics.du.ac.in",
        "phone": "+91-11-24110491",
        "address": "Department of Electronic Science Faculty of Interdisciplinary & Applied Sciences University of Delhi, South Campus New Delhi - 110021",
        "faculty": "Faculty of Interdisciplinary & Applied Sciences",
        "shortHistory": "The Department of Electronic Science specializes in electronics, embedded systems, communication technology, VLSI design, instrumentation, and semiconductor devices. It offers undergraduate, postgraduate, and doctoral programmes while encouraging innovation through research, industry collaborations, and technology-based projects that prepare students for careers in electronics and information technology."
    },
    {
        "slug": "department-of-genetics",
        "name": "Department of Genetics",
        "campus": "South",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://genetics.du.ac.in",
        "email": "head@genetics.du.ac.in",
        "phone": "+91-11-24116247",
        "address": "Department of Genetics Faculty of Interdisciplinary & Applied Sciences University of Delhi, South Campus New Delhi - 110021",
        "faculty": "Faculty of Interdisciplinary & Applied Sciences",
        "shortHistory": "The Department of Genetics is one of India's premier centres for education and research in genetics, genomics, molecular biology, and biotechnology. It offers postgraduate and doctoral programmes with emphasis on human genetics, microbial genetics, plant genetics, bioinformatics, and genetic engineering. The department contributes significantly to research in healthcare, agriculture, and life sciences."
    },
    {
        "slug": "department-of-microbiology",
        "name": "Department of Microbiology",
        "campus": "South",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://microbio.du.ac.in",
        "email": "head@microbio.du.ac.in",
        "phone": "+91-11-24115242",
        "address": "Department of Microbiology Faculty of Interdisciplinary & Applied Sciences University of Delhi, South Campus New Delhi - 110021",
        "faculty": "Faculty of Interdisciplinary & Applied Sciences",
        "shortHistory": "The Department of Microbiology is internationally recognized for excellence in teaching and research in microbiology, immunology, virology, environmental microbiology, industrial microbiology, and microbial biotechnology. The department provides students with extensive laboratory training and research opportunities to address global challenges in health, food security, and environmental sustainability."
    },
    {
        "slug": "department-of-physical-education-sports-sciences",
        "name": "Department of Physical Education & Sports Sciences",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://dpess.du.ac.in",
        "email": "head@dpess.du.ac.in",
        "phone": "+91-11-27667121",
        "address": "Department of Physical Education & Sports Sciences University of Delhi North Campus Delhi - 110007",
        "faculty": "Faculty of Interdisciplinary & Applied Sciences",
        "shortHistory": "The Department of Physical Education & Sports Sciences promotes excellence in sports education, physical fitness, exercise science, sports psychology, sports management, and coaching. The department offers undergraduate, postgraduate, and doctoral programmes while encouraging research and participation in national and international sporting events."
    },
    {
        "slug": "department-of-plant-molecular-biology",
        "name": "Department of Plant Molecular Biology",
        "campus": "South",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://pmb.du.ac.in",
        "email": "head@pmb.du.ac.in",
        "phone": "+91-11-24115115",
        "address": "Department of Plant Molecular Biology Faculty of Interdisciplinary & Applied Sciences University of Delhi, South Campus New Delhi - 110021",
        "faculty": "Faculty of Interdisciplinary & Applied Sciences",
        "shortHistory": "The Department of Plant Molecular Biology focuses on advanced research in plant genetics, molecular biology, biotechnology, crop improvement, and sustainable agriculture. The department offers postgraduate and doctoral programmes and contributes significantly to scientific advancements in plant sciences through innovative research and interdisciplinary collaborations."
    },
    {
        "slug": "department-of-computer-engineering",
        "name": "Department of Computer Engineering",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://technology.du.ac.in",
        "email": "dean_technology@du.ac.in",
        "phone": "+91-11-27006900",
        "address": "Department of Computer Engineering Faculty of Technology University of Delhi North Campus, Delhi - 110007",
        "faculty": "Faculty of Technology",
        "shortHistory": "The Department of Computer Engineering offers comprehensive education in computer science and engineering, focusing on software development, artificial intelligence, machine learning, cybersecurity, cloud computing, data science, and computer networks. The department combines rigorous academic training with practical experience through laboratories, research projects, hackathons, internships, and industry collaborations. Students are encouraged to develop innovative solutions to real-world technological challenges while contributing to research in emerging areas of computing."
    },
    {
        "slug": "department-of-electrical-engineering",
        "name": "Department of Electrical Engineering",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://technology.du.ac.in",
        "email": "dean_technology@du.ac.in",
        "phone": "+91-11-27006900",
        "address": "Department of Electrical Engineering Faculty of Technology University of Delhi North Campus, Delhi - 110007",
        "faculty": "Faculty of Technology",
        "shortHistory": "The Department of Electrical Engineering is dedicated to excellence in teaching, research, and innovation in electrical systems, power engineering, renewable energy, control systems, robotics, electrical machines, and smart grid technologies. The department provides students with strong theoretical foundations complemented by laboratory training, industrial exposure, and research opportunities, preparing them for careers in energy, manufacturing, automation, and public utilities."
    },
    {
        "slug": "department-of-electronics-communication-engineering",
        "name": "Department of Electronics & Communication Engineering",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://technology.du.ac.in",
        "email": "dean_technology@du.ac.in",
        "phone": "+91-11-27006900",
        "address": "Department of Electronics & Communication Engineering Faculty of Technology University of Delhi North Campus, Delhi - 110007",
        "faculty": "Faculty of Technology",
        "shortHistory": "The Department of Electronics & Communication Engineering specializes in electronics, communication systems, embedded systems, VLSI design, wireless technologies, Internet of Things (IoT), signal processing, and semiconductor engineering. Through advanced laboratories, research initiatives, and industry partnerships, the department equips students with the technical knowledge and practical skills required to excel in telecommunications, electronics, automation, and emerging digital technologies."
    },
    {
        "slug": "department-of-music",
        "name": "Department of Music",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://music.du.ac.in",
        "email": "dean_music@du.ac.in",
        "phone": "+91-11-27667608, +91-8860654534",
        "address": "Faculty of Music & Fine Arts University of Delhi North Campus Delhi - 110007.",
        "faculty": "Faculty of Music & Fine Arts",
        "shortHistory": "The Department of Music offers undergraduate, postgraduate, diploma, certificate, and doctoral programmes in Hindustani Classical Vocal Music, Instrumental Music, and Musicology. The department emphasizes practical training alongside theoretical learning and provides students with opportunities to perform, research, and engage with renowned artists and scholars from across the country."
    },
    {
        "slug": "department-of-fine-arts",
        "name": "Department of Fine Arts",
        "campus": "North",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://music.du.ac.in",
        "email": "head@music.du.ac.in",
        "phone": "+91-8287800281, +91-9650929013",
        "address": "Faculty of Music & Fine Arts University of Delhi North Campus Delhi - 110007.",
        "faculty": "Faculty of Music & Fine Arts",
        "shortHistory": "The Department of Fine Arts offers professional education in painting, sculpture, applied arts, printmaking, and visual communication. The department encourages artistic innovation through studio practice, exhibitions, workshops, and interdisciplinary collaborations while preparing students for successful careers in the creative industries, academia, and professional art practice."
    },
    {
        "slug": "department-of-distance-continuing-education",
        "name": "Department of Distance & Continuing Education",
        "campus": "NA",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://sol.du.ac.in",
        "email": "NA",
        "phone": "+91-11-27666776",
        "address": "Faculty of Open Learning University of Delhi Delhi - 110007.",
        "faculty": "Faculty of Open Learning (FOL)",
        "shortHistory": "The Department of Distance & Continuing Education offers a variety of undergraduate, postgraduate, diploma, and certificate programmes through flexible learning modes. It provides comprehensive study materials, online academic resources, learner support services, and examination facilities, enabling students to pursue higher education while balancing personal and professional commitments."
    },
    {
        "slug": "department-of-ayurvedic-unani-medicine",
        "name": "Department of Ayurvedic & Unani Medicine",
        "campus": "NA",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://fmsc.du.ac.in",
        "email": "dean_medical@du.ac.in",
        "phone": "+91-11-27667647",
        "address": "Faculty of Medical Sciences University of Delhi Delhi - 110007.",
        "faculty": "Affiliated Faculties",
        "shortHistory": "The Department of Ayurvedic & Unani Medicine oversees academic programmes in Ayurveda and Unani medicine offered through affiliated institutions. The department promotes quality education, clinical training, research, and the preservation of traditional Indian systems of medicine while encouraging their integration with modern healthcare practices."
    },
    {
        "slug": "department-of-homeopathic-medicine",
        "name": "Department of Homeopathic Medicine",
        "campus": "NA",
        "yearEstablished": "NA",
        "foundingBody": "NA",
        "awards": "NA",
        "studentUnionStatus": "NA",
        "website": "https://fmsc.du.ac.in",
        "email": "dean_medical@du.ac.in",
        "phone": "+91-11-27667647",
        "address": "Faculty of Medical Sciences University of Delhi Delhi - 110007.",
        "faculty": "Affiliated Faculties",
        "shortHistory": "The Department of Homeopathic Medicine is responsible for overseeing homeopathic education and research in affiliated colleges under the University of Delhi. The department focuses on academic excellence, clinical education, and research while promoting evidence-based practices in homeopathic medicine and healthcare."
    }
]
